### ISSUE TITLE
Not compatible with the two stable versions of Forge (v11 b315 or v12 Stable 5)

### ISSUE THREAD

**Issue by noellescoa** [ChasarooniZ/ready-for-the-stage#5]
When I try to download the .zip file using either of the recommended stable versions of Foundry on the Forge, this module states that it is not compatible with the core system (Version 11 Build 315 or Version 12 Stable 5). 

Do you have a recommended version to use this module with?

(P.S. Also, do you have a Discord for easier conversation? I have no idea how to use GitHub...)

**Comment by ChasarooniZ** [comment]
You shouldn't manually download the source code, you should probably just use the manifest URL or grab it from the module list?
